### ISSUE TITLE
SUMP todo list

### ISSUE THREAD

**Issue by feilongfl** [feilongfl/ZephyrSUMP#1]
- SUMP Functions
    - [ ] add trigger setting support
    - [ ] variable sampling speed support
- Devices
    - [ ] Common
      - [x] GPIO Sample Mode
    - [ ] Arm
      - [x] GPIO Sample By asm
      - [ ] AT32
        - [ ] GPIO Sample By TIMER & DMA
      - [ ] GD32
      - [ ] STM32
- [ ] project
  - [ ] CI
  - [ ] Drop zephyr files, make out-of-tree Application
